[package]
name = "dismem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
ctrlc = "3.2.1"
clap = "3.0.5"
num_cpus = "1.13.1"
crossbeam = "0.8.1"